name: CI

on:
  push:
    branches:
      - master
      - pass1-modernize
      - pass2-parity
      - pass3-api-coverage
  pull_request:

jobs:
  tests:
    name: Tests (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            tox-env: py310
          - python-version: "3.11"
            tox-env: py311
          - python-version: "3.12"
            tox-env: py312
          - python-version: "3.13"
            tox-env: py313
          - python-version: "3.14"
            tox-env: py314
          - python-version: "3.15"
            tox-env: py315

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install tox
        run: python -m pip install --upgrade pip tox

      - name: Run test env
        run: tox -e ${{ matrix.tox-env }}

      - name: Upload coverage to Codecov
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.${{ matrix.tox-env }}.xml
          flags: ${{ matrix.tox-env }}
          fail_ci_if_error: true
          verbose: true

  quality:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install tox
        run: python -m pip install --upgrade pip tox

      - name: Run lint and type checks
        run: tox -e lint,type
